const TEMPLATE = {
    'DB_DE_Charakterbogen_ausfuellbar_v0.8': 'DB_DE_Charakterbogen_ausfuellbar_v0.8.pdf'
}

const FIELD = {
    'DB_DE_Charakterbogen_ausfuellbar_v0.8.pdf': {
        PLAYER: 'Gespielt von',
        KIN: 'Volk',
        AGE: 'Alter',
        PROFESSION: 'Beruf',
        WEAKNESS1: 'Schwächen 1',
        WEAKNESS2: 'Schwächen 2',
        NAME: 'Name',
        STR: 'STR',
        CON: 'KON',
        AGL: 'GEW',
        INT: 'INT',
        WIL: 'WIL',
        CHA: 'CHA',
        DAMAGE_BONUS_STR: 'Schadensbonus STR',
        DAMAGE_BONUS_AGL: 'Schadensbonus GEW',
        MOVEMENT: 'Bewegung',
        HP: 'TP',
        WP: 'WP',
        ABILITY: nr => `Talente & Zauber ${nr+1}`,
        INVENTORY: nr => `Inventar ${nr+1}`,
        GOLD: 'Goldstücke',
        SILVER: 'Silberstücke',
        COPPER: 'Kupferstücke',
        ENCUMBRANCE: 'Traglast',
        ARMOR: 'Rüstung',
        HELMET: 'Helm',
        SKILL: {
            Acrobatics: 'Fertigkeiten 1',
            Evade: 'Fertigkeiten 2',
            BeastLore: 'Fertigkeiten 3',
            Performance: 'Fertigkeiten 4',
            SpotHidden: 'Fertigkeiten 5',
            Bartering: 'Fertigkeiten 6',
            SleightOfHand: 'Fertigkeiten 7',
            Languages: 'Fertigkeiten 8',
            Crafting: 'Fertigkeiten 9',
            Healing: 'Fertigkeiten 10',
            Sneaking: 'Fertigkeiten 11',
            HuntingFishing: 'Fertigkeiten 12',
            MythsLegends: 'Fertigkeiten 13',
            Riding: 'Fertigkeiten 14',
            Swimming: 'Fertigkeiten 15',
            Seamanship: 'Fertigkeiten 16',
            Bluffing: 'Fertigkeiten 17',
            Persuasion: 'Fertigkeiten 18',
            Awareness: 'Fertigkeiten 19',
            Bushcraft: 'Fertigkeiten 20',
        },
        WEAPON_SKILL: {
            Crossbows: 'KF 1',
            Axes: 'KF 2',
            Bows: 'KF 3',
            Hammers: 'KF 4',
            Knives: 'KF 5',
            Brawling: 'KF 6',
            Slings: 'KF 7',
            Swords: 'KF 8',
            Spears: 'KF 9',
            Staves: 'KF 10',
        },
        SECONDARY_SKILLS: nr => `Sekundäre Fertigkeiten ${nr+1}`,
        APPEARANCE: nr => `Erscheinungsbild ${nr+1}`,
        MEMENTO: nr => `Memento ${nr+1}`,
        WEAPON_SHIELD: nr => `Waffe/Schild ${nr+1}`,
        GRIP: nr => `Griff ${nr+1}`,
        RANGE: nr => `Reichweite ${nr+1}`,
        DAMAGE: nr => `Schaden ${nr+1}`,
        DURABILITY: nr => `Haltbarkeit ${nr+1}`,
        FEATURES: nr => `Merkmale ${nr+1}`,
    }
};
